### ISSUE TITLE
Validate signature returning false from Verotel/FlexPay/Client

### ISSUE THREAD

**Issue by galiteintechnologies** [verotel/flexpay-php-client#2]
Validate signature returning false from Verotel/FlexPay/Client

File: https://github.com/verotel/flexpay-php-client/blob/master/src/Verotel/FlexPay/Client.php#L97

I saw function **validate_signature** is returning false. I have attached an image. Can anyone please help?

https://github.com/verotel/flexpay-php-client/blob/master/src/Verotel/FlexPay/Client.php#L97

https://controlcenter.verotel.com/website-FlexPay-postbackTest?postback=subscriptionRebill&website_id=123722

![rebill-postback-1](https://user-images.githubusercontent.com/20535840/149349833-d50a8a1e-5e4d-4b42-a8b7-b1916b67ce7d.png)

Thank you

**Comment by PunchyRascal** [comment]
Without sharing your secret key, can you show your code?

**Comment by galiteintechnologies** [comment]
![rebill-5-1](https://user-images.githubusercontent.com/20535840/149349890-039245c8-dc3d-4de8-b3d9-9c4ba3686a89.png)

Hello @PunchyRascal 

Thank you for the faster response.

I have attached an image.

Thank you

**Comment by PunchyRascal** [comment]
Right. If you could share the whole URL of the postback, including all GET parameters, I could test this for you to see if the library works as it should. The postback URL should not contain any sensitive data.

**Comment by PunchyRascal** [comment]
It looks like you are using the wrong Flexpay secret. You seem to be using  a secret of website 111454 while testing postback for website 123722.

**Comment by galiteintechnologies** [comment]
Hello @PunchyRascal ,

Yes, your help worked.

Thank you very much :)

You can close the issue.
